services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cve_sync
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend_app
    restart: always
    env_file: ".env"
    depends_on:
      - db
    ports:
      - "8000:8000"

  sync-worker:
    build: .
    container_name: nvd_sync_worker
    restart: always
    env_file:
      - ".env"
    depends_on:
      - db
    command: python -m app.workers.nvd_sync


volumes:
  postgres_data: