"""add row created_at in sync models

Revision ID: 04774f412b0f
Revises: e01c2856ebf4
Create Date: 2026-06-30 12:43:47.820639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04774f412b0f'
down_revision: Union[str, Sequence[str], None] = 'e01c2856ebf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_cve_records_cve_id'), table_name='cve_records')
    op.drop_index(op.f('ix_cve_records_cvss_base_severity'), table_name='cve_records')
    op.drop_table('cve_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cve_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cve_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('source_identifier', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_modified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('vuln_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cvss_base_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('cvss_base_severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('cvss_vector', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('cve_records_pkey'))
    )
    op.create_index(op.f('ix_cve_records_cvss_base_severity'), 'cve_records', ['cvss_base_severity'], unique=False)
    op.create_index(op.f('ix_cve_records_cve_id'), 'cve_records', ['cve_id'], unique=True)
    op.create_table('sync_runs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('added_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sync_runs_pkey'))
    )
    # ### end Alembic commands ###
