"""make affected product cpe uri nullable

Revision ID: 6f5051e52409
Revises: d1371e3bc8c2
Create Date: 2026-07-04 17:38:31.514405

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6f5051e52409"
down_revision: Union[str, Sequence[str], None] = "d1371e3bc8c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cve_affected_products",
        "cpe_uri",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cve_affected_products",
        "cpe_uri",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
    )
    # ### end Alembic commands ###
